spring:
  application:
    name: split-pro
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/splitpro}
      auto-index-creation: true
  
  # security:
  #   require-ssl: false

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-message: on-param
    include-stacktrace: on-param

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.splitpro: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configuration
splitpro:
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      access-token-expiry: 900000  # 15 minutes
      refresh-token-expiry: 604800000  # 7 days
      cookie-name: split-pro-token
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}
  rate-limit:
    auth:
      requests-per-minute: 5