spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  
  # security:
  #   require-ssl: true

server:
  forward-headers-strategy: native
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    com.splitpro: INFO
    org.springframework.security: WARN
    root: WARN

splitpro:
  security:
    jwt:
      secret: ${JWT_SECRET}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}